import { IProduct } from "./product";

export const products: IProduct[] = [{
    currency: "₹",
    description: "Duis bibendum. Morbi non quam nec dui luctus rutrum.",
    featuredimage: "http://via.placeholder.com/200x250",
    id: 1,
    identifier: "Soda Water - Club Soda, 355 Ml",
    images: [],
    price: 514,
    sku: "",
    title: "Nantucket Orange Juice",
}, {
    currency: "₹",
    description: "Vivamus tortor. Duis mattis egestas metus.",
    featuredimage: "http://via.placeholder.com/200x250",
    id: 2,
    identifier: "Bouillion - Fish",
    images: [],
    price: 390,
    sku: "̦",
    title: "Wine - Niagara Peninsula Vqa",
}, {
    currency: "₹",
    description: "In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl.",
    featuredimage: "http://via.placeholder.com/200x250",
    id: 3,
    identifier: "Ginger - Crystalized",
    images: [],
    price: 140,
    sku: "",
    title: "Ginger - Crystalized",
}, {
    currency: "₹",
    description: "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.",
    featuredimage: "http://via.placeholder.com/200x250",
    id: 4,
    identifier: "Muffin Chocolate Individual Wrap",
    images: [],
    price: 111,
    sku: "",
    title: "V8 Pet",
}, {
    currency: "₹",
    description: "In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.",
    featuredimage: "http://via.placeholder.com/200x250",
    id: 5,
    identifier: "Ginger - Fresh",
    images: [],
    price: 148,
    sku: "",
    title: "Soup - Campbells Chili Veg",
}, {
    currency: "₹",
    description: "Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.",
    featuredimage: "http://via.placeholder.com/200x250",
    id: 6,
    identifier: "Flour - Teff",
    images: [],
    price: 782,
    sku: "",
    title: "Vanilla Beans",
}, {
    currency: "₹",
    description: "Morbi non quam nec dui luctus rutrum.",
    featuredimage: "http://via.placeholder.com/200x250",
    id: 7,
    identifier: "Stock - Beef, White",
    images: [],
    price: 435,
    sku: "",
    title: "Lettuce - Red Leaf",
}, {
    currency: "₹",
    description: "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.",
    featuredimage: "http://via.placeholder.com/200x250",
    id: 8,
    identifier: "Crab - Soft Shell",
    images: [],
    price: 935,
    sku: "",
    title: "Lamb - Rack",
}, {
    currency: "₹",
    description: "Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",
    featuredimage: "http://via.placeholder.com/200x250",
    id: 9,
    identifier: "Shrimp - Black Tiger 6 - 8",
    images: [],
    price: 209,
    sku: "",
    title: "Molasses - Fancy",
}, {
    currency: "₹",
    description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.",
    featuredimage: "http://via.placeholder.com/200x250",
    id: 10,
    identifier: "Muffin Mix - Oatmeal",
    images: [],
    price: 247,
    sku: "",
    title: "Foam Cup 6 Oz",
}];
